# Generated by Django 5.0.6 on 2024-06-01 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Sensor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("OUTDOOR", "Outdoor"),
                            ("INDOOR", "Indoor"),
                            ("ALL_PURPOSE", "All Purpose"),
                        ],
                        default="ALL_PURPOSE",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("DAMAGED", "Damaged"),
                            ("IN_REPAIR", "In Repair"),
                        ],
                        default="ACTIVE",
                    ),
                ),
                ("model", models.CharField(max_length=255)),
                ("installation_date", models.DateTimeField()),
            ],
        ),
    ]
