# Generated by Django 5.0.6 on 2024-06-01 08:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("sensor", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SensorData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pm_2_5_level",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "pm_10_level",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "co_2_level",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "sensor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sensor.sensor",
                    ),
                ),
            ],
        ),
    ]
