# Generated by Django 5.0.6 on 2024-06-03 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sensordata",
            old_name="co_2_level",
            new_name="humidity",
        ),
        migrations.RenameField(
            model_name="sensordata",
            old_name="pm_10_level",
            new_name="temperature",
        ),
        migrations.RenameField(
            model_name="sensordata",
            old_name="pm_2_5_level",
            new_name="wind_speed",
        ),
    ]
